apiVersion: v1
kind: Namespace
metadata:
  name: identity
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: identity-svc
  namespace: default
  labels:
    name: service-svc
    env: dev
spec:
  type: LoadBalancer #NodePort,ClusterIP,LoadBalancer --> Ingress Controller:nginx,HAProxy
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    name: identity-app
---
apiVersion: v1
data:
  .dockerconfigjson: 
  kind: Secret
metadata:
  creationTimestamp: null
  name: acr-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-deploy
  namespace: default
  labels:
    name: identity-app
    env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: identity-app
  template:
    metadata:
      namespace: default
      labels:
        app: identity-app
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
      - image: identityservice.azurecr.io/identityservice:${{ github.run_id }}
        name: identityservice
        resources:
          requests:
            cpu: 0.5
            memory: "500Mi" # See: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#how-pods-with-resource-requests-are-scheduled
          limits:
            cpu: 2
            memory: "1000Mi"
        env:
        - name: testEnv
          value: "12345"
        ports:
        - containerPort: 8000
          name: identity-app
        imagePullPolicy: Always
      restartPolicy: Always
