apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: identity-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: identityapp
    spec:
      containers:
        - name: identityapp
          image: identityservice.azurecr.io/serviceone:${{ github.run_id }}
          ports:
          - containerPort: 80
