apiVersion: v1
kind: Namespace
metadata:
  name: identity
  namespace: default
---
apiVersion: v1
kind: Service
metadata:
  name: identity-svc
  namespace: default
  labels:
    name: service-svc
    env: dev
spec:
  type: LoadBalancer #NodePort,ClusterIP,LoadBalancer --> Ingress Controller:nginx,HAProxy
  ports:
  - name: http
    port: 8000
    targetPort: 8000
  selector:
    name: identity-app
