name: CI

on:
  push:
    branches: [ 3934 ]
  pull_request:
    branches: [ 3934 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

