name: Python CI
'on':
  push:
   branches:
     - mert
  pull_request:
    branches:
      - sanem
      - mert
jobs:
  build:
    if: github.event_name == 'push'
    env:
      JOB_STATUS_UNIT: ok
      JOB_STATUS_SCA: ok
      GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: '${{ runner.os }}-pip-${{ hashFiles(''**/requirements.txt'') }}'
          restore-keys: |
            ${{ runner.os }}-pip-
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: '${{ runner.os }}-pip-${{ hashFiles(''**/requirements.txt'') }}'
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Slack Notification for Unit Tests
        uses: bryan-nice/slack-notification@master
        env:
          SLACK_WEBHOOK: '${{ secrets.SLACK_WEBHOOK }}'
          SLACK_TITLE: Failure
          SLACK_MESSAGE: "You cannot pass the tests... Check your unit tests! workflow: ${{ github.workflow }} run id: ${{ github.run_id\t}}\t"
        if: failure()
      - name: Set Unit Test Status
        id: unitslack
        run: |
          echo "::set-output name=JOB_STATUS_UNIT::failed"
        if: failure()
      - name: Check outputs
        run: >
          echo "Pull Request Number - ${{ steps.test.outputs }}"

          echo "Pull Request Number - ${{
          steps.unitslack.outputs.JOB_STATUS_UNIT }}"

          echo "Pull Request Number - $JOB_STATUS_UNIT"
        if: always()
      - name: Run Sonar for vulernability check in dependencies
        run: |
          pip install safety
          safety check --full-report
     # - name: Analyze with SonarCloud
     #   uses: sonarsource/sonarcloud-github-action@master
     #   env:
     #     GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
     #     SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}'
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: '${{ secrets.SNYK_TOKEN }}'
        with:
          args: '--severity-threshold=high'
          command: monitor
      - name: Slack Notification for Snyk
        if: steps.unitslack.outputs.JOB_STATUS_UNIT != 'failed' && failure()
        uses: bryan-nice/slack-notification@master
        env:
          SLACK_WEBHOOK: '${{ secrets.SLACK_WEBHOOK }}'
          SLACK_TITLE: Failure
          SLACK_MESSAGE: "You got an error during SCA Step, Snyk! workflow: ${{ github.workflow }} run id: ${{ github.run_id\t}}\t"
      - uses: azure/docker-login@v1
        with:
          login-server: identityservice.azurecr.io
          username: '${{ secrets.REGISTRY_USERNAME }}'
          password: '${{ secrets.REGISTRY_PASSWORD }}'
      - run: |
          docker build . -t identityservice.azurecr.io/serviceone:${{ github.run_id }}
          docker push identityservice.azurecr.io/serviceone:${{ github.run_id }}

terraform:
    name: 'Terraform'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: 'Terraform Init'
        run: terraform init ./terraform
      - name: 'Terraform Format'
        run: terraform fmt -check ./terraform
      - name: 'Terraform Plan'
        run: terraform plan ./terraform
      - name: Terraform Apply
        if: github.ref == 'refs/heads/mert' && github.event_name == 'push'
        run: terraform apply -auto-approve ./terraform

  staging:
    if: github.run_id != 'refs/heads/mert' &&  github.event_name == 'push'
    needs: [terraform, build]    
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: identity-aks
        resource-group: identity-aks-rg
      id: login
    - uses: azure/k8s-create-secret@v1
      with:
        container-registry-url: identityservice.azurecr.io
        container-registry-username: '${{ secrets.REGISTRY_USERNAME }}'
        container-registry-password: '${{ secrets.REGISTRY_PASSWORD }}'
        secret-name: identity-k8s-secret
    - uses: azure/k8s-deploy@v1
      with:
        manifests: |
          ./kubernetes/deployment.yml
        images: 'identityservice.azurecr.io/serviceone:${{ github.run_id }}'
        imagepullsecrets: |
          identity-k8s-secret
        kubectl-version: latest
    - name: Slack Notification for Build
      uses: bryan-nice/slack-notification@master
      env:
        SLACK_WEBHOOK: '${{ secrets.SLACK_WEBHOOK }}'
        SLACK_TITLE: Build
        SLACK_MESSAGE: >-
          Your build is completed! successfully pushed to container
          registry  identityservice.azurecr.io/serviceone:${{ github.run_id
          }}
