# CI using earthly
name: CI

on:
  push:
    branches: [ mert ]
  pull_request:
    branches: [ mert ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      #url_instead_of: "https://github.com/=git@github.com:"
