# CI using earthly
name: CI

on:
  push:
    branches: [ mert ]
  pull_request:
    branches: [ mert ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      #url_instead_of: "https://github.com/=git@github.com:"
      url_instead_of: "git@github.com/=https://github.com:"
      FORCE_COLOR: 1
    steps:
    - uses: actions/checkout@v2
    - name: Put back the git branch into git (Earthly uses it for tagging)
      run: |
        branch=""
        if [ -n "$GITHUB_HEAD_REF" ]; then
          branch="$GITHUB_HEAD_REF"
        else
          branch="${GITHUB_REF##*/}"
        fi
        git checkout -b "$branch" || true
    - name: ACR Login
      uses: azure/docker-login@v1
      with:
        login-server: identityservice.azurecr.io
        username: '${{ secrets.REGISTRY_USERNAME }}'
        password: '${{ secrets.REGISTRY_PASSWORD }}'
    - name: Download latest earth
      run: "sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/download/v0.3.10/earth-linux-amd64 -O /usr/local/bin/earth && chmod +x /usr/local/bin/earth'"
    - name: Earth version
      run: earth --version
    - name: Run build
      run: earth --push +build
