name: Terraform Validate

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
        steps:
    #  - name: "Azure Login"
    #    uses: azure/login@v1.1
    #    with:
    #      creds: ${{ secrets.AZURE_CREDENTIALS }}
    #  - name: "Checkout"
    #    uses: actions/checkout@master
